deployment:
  tasks:
    - export DEPLOYPATH=/home/usersumak/public_html
    - /bin/rsync -av --delete \
        --exclude='.git' \
        --exclude='node_modules' \
        --exclude='.env' \
        ./public/ $DEPLOYPATH/
    - if ! grep -q "APP_KEY=base64" $DEPLOYPATH/.env; then \
        cd $DEPLOYPATH && php artisan key:generate; \
      fi
    - cd $DEPLOYPATH && composer install --no-dev
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan cache:clear
